<a href="https://colab.research.google.com/github/fjnarvaezo1-dotcom/Lineal-regresion-machine-learning/blob/main/leads_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<div align="center">
  <img src="https://www.unad.edu.co/images/footer/logo-unad-acreditacion-min.png" width="580" height="120" />
</div>

<p style="text-align: center;">Curso: Gestión de Proyectos para la Analítica</p>
<p style="text-align: center;">Código Curso: 203008074A_2204</p>
<p style="text-align: center;">Grupo: 203008074_22</p>


<p style="text-align: center;">Fase 2 - Planificación y Arquitectura de Datos en Proyectos Analíticos</p>
<p style="text-align: center;">Presentado por: Francisco Javier Narvaez Ortiz</p>
<p style="text-align: center;">Código: 1023915471</p>
<p style="text-align: center;">Tutor(a): JORGE ELIECER OSPINO PORTILLO</p>
<p style="text-align: center;">UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA - UNAD</p>
<p style="text-align: center;">Medellín</p>
<p style="text-align: center;">2026</p>

## Dataframe numero 1 ajuste de informacion

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
ruta_archivo = "/content/drive/MyDrive/GESTIÓN DE PROYECTOS PARA LA ANALÍTICA - (203008074A_2204)/Leads_Detail.csv"

In [ ]:
import pandas as pd
df = pd.read_csv(ruta_archivo, sep=',')
df = pd.DataFrame(df)
df.head(60000)

,lead_id,campaign_id,contact_date,responded,scheduled_demo,closed_deal,deal_value
0,LD001,CAM027,2024-02-01,True,False,True,9771.31
1,LD002,CAM055,2024-02-02,True,False,True,12446.13
2,LD003,CAM033,2024-02-03,True,False,False,3096.32
3,LD004,CAM068,2024-02-04,False,True,True,164.94
4,LD005,CAM066,2024-02-05,True,False,False,2053.28
...,...,...,...,...,...,...,...
75,LD076,CAM009,2024-04-16,True,True,True,8519.18
76,LD077,CAM074,2024-04-17,False,True,False,13732.32
77,LD078,CAM052,2024-04-18,True,True,False,509.19
78,LD079,CAM057,2024-04-19,True,True,True,10461.30
79,LD080,CAM026,2024-04-20,False,False,True,4460.24

## Dataframe Numero 2

In [ ]:
ruta = "/content/drive/MyDrive/GESTIÓN DE PROYECTOS PARA LA ANALÍTICA - (203008074A_2204)/campaign_performance_data.csv"

In [ ]:
df_2 = pd.read_csv(ruta, sep=',')
df_2 = pd.DataFrame(df_2)
df_2.head(100)

,campaign_id,ad_platform,campaign_name,industry,start_date,end_date,impressions,clicks,cost_usd,conversions,conversion_value,leads,ctr,roas,region
0,CAM001,Meta Ads,Campaña ERP 1,Agroindustria,2024-01-01,2024-01-31,238576,1943,9950.95,100,20581.44,67,0.022,1.53,Argentina
1,CAM002,Google Ads,Campaña ERP 2,Cross-sector,2024-01-08,2024-02-07,239170,8780,5229.50,130,25876.02,53,0.033,4.07,Perú
2,CAM003,Meta Ads,Campaña ERP 3,Salud,2024-01-15,2024-02-14,23545,3076,3516.04,122,5341.45,182,0.016,3.79,Chile
3,CAM004,Meta Ads,Campaña ERP 4,Tecnología,2024-01-22,2024-02-21,137659,2059,8951.45,52,9500.56,169,0.058,1.09,Argentina
4,CAM005,Google Ads,Campaña ERP 5,HR Services,2024-01-29,2024-02-28,207271,5859,7729.47,93,20738.50,182,0.040,1.20,Perú
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,CAM076,LinkedIn,Campaña ERP 76,Agroindustria,2025-06-09,2025-07-09,236814,9107,4854.83,221,14607.58,32,0.041,2.64,Argentina
76,CAM077,LinkedIn,Campaña ERP 77,Finanzas,2025-06-16,2025-07-16,247714,7783,7196.50,281,17242.31,62,0.014,1.36,Colombia
77,CAM078,Meta Ads,Campaña ERP 78,Salud,2025-06-23,2025-07-23,152483,4742,1523.74,253,3818.30,174,0.054,0.75,Colombia
78,CAM079,Meta Ads,Campaña ERP 79,Cross-sector,2025-06-30,2025-07-30,143983,7779,9236.92,168,18964.58,211,0.056,3.13,Argentina
79,CAM080,LinkedIn,Campaña ERP 80,Tecnología,2025-07-07,2025-08-06,208342,8308,4981.17,196,15835.42,92,0.013,1.59,Argentina